#!/bin/bash

nomes=( )
telefones=( )

saida_case="nao"
until [ $saida_case = "sim" ];
do

clear
echo " ### Agenda tabajara ###"
echo "Escolha uma das opções abaixo:"
echo #Pular linha
echo "[1] Cadastrar contato"
echo "[2] Buscar contato"
echo "[3] Listar contato"
echo "[4] Sair"
read opcao


case $opcao in
	1)
	saida_cadastro="nao"	
	until [ $saida_cadastro = "sim" ];
	do	
		clear		
		echo " ### Cadastro de contatos ### "		
		echo		
		echo "[1] Cadastrar um contato"
		echo "[2] Sair"	
		read cadastrar
		
		if [ $cadastrar -eq 1 ];
		then
			saida="nao"
			while [ $saida = "nao" ];
			do
				echo "Digite o nome do contato: "
				read nome
				echo "Digite o telefone no contato: "
				read telefone
				if [ -z $nome ] || [ -z $telefone ]; #Verifica se as variaveis sao nulas
				then
					echo "--- Campos obrigatórios, digite novamente ---"	
				else
					nomes+=( "$nome" )
					telefones+=( "$telefone" )
					saida="sim"
					echo "--- Cadastro realizado com sucesso ---"
					sleep 1
				fi
			done
		elif [ $cadastrar -eq 2 ];
		then
			saida_cadastro="sim"
		else
			clear			
			echo "Escolha uma das opções"
			echo
		fi
	done ;;

	2)
	saida_busca="nao"
	until [ $saida_busca = "sim" ];
	do	
		echo " ### Busca contatos ### "
		echo
		echo "[1] Buscar por nome"
		echo "[2] Buscar por telefone"
		echo "[3] Sair"
		echo -n "Escolha uma das opções: "
		read opcao_busca
	
		nome_encontrado="nada"
		telefone_encontrado="nada"	
		if [ $opcao_busca -eq 1 ]; #Efetua busca por nome
		then
			echo -n "Digite o nome para busca: "		
			read nome_busca
			for (( count = 0; count <= ${#nomes[@]}; count++ ));
			do
				if [ "$nome_busca" = "${nomes[count]}" ];		
				then
					nome_encontrado=${nomes[count]}
					telefone_encontrado=${telefones[count]}
				fi
				
			done
			# Caso encontre o contato, exibe na tela
			if [ $nome_encontrado = "nada" ] && [ $telefone_encontrado = "nada" ];
			then
				echo "Contado não encontrado =/"
				echo
				sleep 1
				
			else
				echo "--- Contato encontrado ---"
				echo $nome_encontrado
				echo $telefone_encontrado
				echo
				sleep 1
			fi
	
		elif [ $opcao_busca -eq 2 ]; #Efetua busca por telefone
		then
			echo -n "Digite o telefone para busca: "		
			read telefone_busca
			for (( count = 0; count <= ${#telefones[@]}; count++  ));
			do
				
				if [ "$telefone_busca" = "${telefones[count]}" ];		
				then
					nome_encontrado=${nomes[count]}
					telefone_encontrado=${telefones[count]}
				fi
			done
			# Caso encontre o contato, exibe na tela
			if [ $nome_encontrado = "nada" ] && [ $telefone_encontrado = "nada" ];
			then
				echo "Contado não encontrado =/"
				echo
				sleep 1
				
			else
				echo "--- Contato encontrado ---"
				echo $nome_encontrado
				echo $telefone_encontrado
				echo
				sleep 1
			fi
		
		elif [ $opcao_busca -eq 3 ]; # Sai da opção escolhida
		then
			saida_busca="sim"
		
		else #Repete caso a opção seja inválida
			echo "Opção inválida, escolha uma das opções abaixo"
			echo
			sleep 1
		fi
	done ;;
	
	3)
	saida_listagem="nao"
	until [ $saida_listagem = "sim" ];
	do
		echo " ### Listagem de contatos ### "
		echo
		echo "[1] Listar os contatos"
		echo "[2] Sair"
		read opcao_lista		
		
		if [ $opcao_lista -eq 1 ];
		then
			count=0			
			for contato in ${nomes[*]};
			do
								
				echo				
				echo $contato
				echo ${telefones[count]}
				(( count+=1 ))
			done
			echo # Pula linha no final da listagem
		
		elif [ $opcao_lista -eq 2 ];
		then
			saida_listagem="sim"

		else
			echo "Opção inválida. Digite uma das opções"
			echo
		fi
	done ;;
				



	4)
		saida_case="sim";;
esac
done
